### Recuperar todas los usuarios
GET http://localhost:1234/multitask

### Recuperar un usuario por email
GET http://localhost:1234/multitask/juan@example.com


### obtener un código para iniciar sesión

GET http://localhost:1234/multitask/generate-code/3shyworks@gmail.com

### obtener persona por email

GET http://localhost:1234/multitask/person/3shyworki@gmail.com

### Crear persona y usuario

POST http://localhost:1234/multitask/person
Content-Type: application/json

{
  "nombre": "xd",
  "apellidos": "a",
  "tipo_documento": "C.C",
  "cedula": "1234",
  "correo": "juan@example.com",
  "direccion": "Calle 123",
  "telefono": "987654321",
  "fecha_nacimiento": "1990-01-01",
  "genero": "Masculino",
  "password": "123",
  "nUsuario": "jua2456",
  "tipoUsuario": "Administrador"
}


### Modificar personas

PUT http://localhost:1234/multitask/person/3shyworki@gmail.com
Content-Type: application/json

{
  "nombre": "ASA",
  "apellidos": "a",
  "direccion": "Calle 123",
  "correo": "3shyworki@gmail.com",
  "password": "1234",
  "telefono": "987654321"

}

### OBTENER TODOS LOS EMPLEADOS

GET http://localhost:1234/multitask/employee


### OBTENER SERVICIOS SEGÚN SECTOR

GET http://localhost:1234/multitask/service/Metales
